feat: alternative visual representation
jon-whit/openfga-graphviz-gen pull request #2
Opened 2023-08-17 13:54 UTC by jpadilla

Related to https://github.com/openfga/openfga/pull/934

Generating PNGs for all example models

```
for f in ./examples/*.fga; do go run main.go --model-path "$f" | dot -Tpng > "${f%.*}.png"; done
```

2023-08-17 17:41 UTC, miparnisari requested changes

2023-08-17 17:41 UTC, miparnisari commented on examples/ttu.png
i think this drawing should be like this:

<img width="953" alt="image" src="https://github.com/jon-whit/openfga-graphviz-gen/assets/5374887/9c21dcb7-e29a-4c41-b0a1-dfe298393bc6">

2023-08-17 17:59 UTC, miparnisari commented on examples/ttu.png
Another example: 
<img width="1919" alt="image" src="https://github.com/jon-whit/openfga-graphviz-gen/assets/5374887/def63314-48fa-4a1e-8747-9cb23f3c8787">

2023-08-18 00:49 UTC, jpadilla commented on examples/ttu.png
fixed

2023-08-18 00:53 UTC, miparnisari approved these changes

2023-08-18 00:54 UTC, merged